export const ROUTES = {
  ONBOARDING: 'Onboarding',
  LANDING: 'Landing',
  REGISTER: 'Register',
  LOGIN: 'Login',
  RESET_PASSWORD: 'ResetPassword',
  VERIFY: 'Verify',
  FORGOT: 'Forgot',
  ALLOW_LOCATION: 'AllowLocation',
  ALLOW_NOTIFICATION: 'AllowNotication',
  COMPLETE_PROFILE: 'CompleteProfile',
  COMPLETE_PROFILE_THANK_YOU: 'CompleteProfileThankYou',
  MAIN: 'Main',
  YOUR_WORLD: 'YourWorld',
};
